services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/
      - ME_CONFIG_BASICAUTH=false
  rabbitmq:
    build:
      context: .
      dockerfile: RabbitMqDockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 61613:61613
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
volumes:
  mongo: { }
  rabbitmq: { }
