spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27020
      database: messenger
      authentication-database: admin
  rabbitmq:
    username: admin
    password: admin
    port: 61613
    host: localhost
    virtual-host: /stomp
auth:
  jwt:
    signing-key: aW5zdGFodWIoY2h1cGFjaHVwczg0LGs0cjNsMW5zLHN3dHk0NSxpcmluYWZlZG9yb3ZpY2gxOTk1KQ==
    expiration:
      access-token: 5000 #1800000 # 30 min
      refresh-token: 604800000 # 1 week
  url: /api/v1/auth
storage:
  endpoint: http://127.0.0.1:9000
  username: minioadmin
  password: minioadmin
  region: ru-central1
  avatar-bucket: avatar
  file-bucket: file

logging:
  level:
    org.springframework.web: DEBUG
#    org.springframework.messaging.simp.SimpMessagingTemplate: DEBUG